// Angular/ToDoList/src/app/page-list/page-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from '../_interface/todo';
import { Eventping } from '../_interface/eventping';
import { faChevronUp, faChevronDown } from '@fortawesome/free-solid-svg-icons';
import { LocalStorageService } from '../_service/localstorage.service';

@Component({
  selector: 'app-page-list',
  templateUrl: './page-list.component.html',
  styleUrls: ['./page-list.component.sass']
})
export class PageListComponent implements OnInit {

  faUp = faChevronUp;
  faDown = faChevronDown;
  public toDoShow: boolean;
  public toDoDoneShow: boolean;
  public $todos: Todo[];
  public $todosdone: Todo[];

  constructor(private lss: LocalStorageService) {
    this.toDoShow = true;
    this.toDoDoneShow = false;
    this.$todos = lss.getTodos(false);
    this.$todosdone = lss.getTodos(true);
  }

  ngOnInit(): void {
  }

  public createToDo(event: Todo): void {
    this.lss.addTodo(event.label, event.status);
    const allTodos:Todo[] = this.lss.getTodos(event.status);
    this.$todos.push(allTodos[allTodos.length-1]);
  }

  public update(event: Eventping): void {
    if( 'check' === event.label){
      if(!event.object.status){
        this.$todosdone.splice(this.$todosdone.indexOf(event.object), 1);
        this.$todos.push(event.object);
      }else{
        this.$todos.splice(this.$todos.indexOf(event.object), 1);
        this.$todosdone.push(event.object);
      }
      this.lss.editTodo(event.object.id, event.object.label, event.object.status);
    }
    if( 'delete' === event.label) {
      if(event.object.status) {
        this.$todosdone.splice(this.$todosdone.indexOf(event.object), 1);
      }else{
        this.$todos.splice(this.$todos.indexOf(event.object), 1);
      }
      this.lss.removeTodo(event.object.id);
    }
    if ('label' === event.label) {
      if (event.object.status) {
        this.$todosdone.forEach((toDo: Todo) => {
          if(toDo.id === event.object.id){
            toDo.label = event.object.label;
            console.log(event.object.label);
            this.lss.editTodo(event.object.id, event.object.label, event.object.status);
          }
        });
      } else {
        this.$todos.forEach((toDo: Todo) => {
        if (toDo.id === event.object.id) {
          toDo.label = event.object.label;
          console.log(event.object.label);
          this.lss.editTodo(event.object.id, event.object.label, event.object.status);
        }
      });
      }
    }
  }

}

<app-template-todo-form (ping)="createToDo($event)"></app-template-todo-form>

<div class="container-md">
    <div class="page-list">
        <h3 (click)="toDoShow=!toDoShow" class="pl-title justify-content-between" [class.open]="toDoShow">
            <div class="left">
                Offen
                <span class="badge bg-secondary pl-num">{{ $todos.length }}</span>
            </div>
            <div class="right">
                <span class="chevron-toggle">
                    <fa-icon *ngIf="!toDoShow" [icon]="faDown"></fa-icon>
                    <fa-icon *ngIf="toDoShow" [icon]="faUp"></fa-icon>
                </span>
            </div>
        </h3>
        <div *ngIf="toDoShow"  class="todo-elements">
            <app-template-todo (ping)="update($event)" [toDo$]="toDo" *ngFor="let toDo of $todos"></app-template-todo>
        </div>
    </div>

    <hr>
    
    <div class="page-list">
        <h3 (click)="toDoDoneShow=!toDoDoneShow" class="pl-title justify-content-between" [class.open]="toDoDoneShow">
            <div class="left">
                Erledigt
                <span class="badge bg-secondary pl-num">{{ $todosdone.length }}</span>
            </div>
            <div class="right">
                <span class="chevron-toggle">
                    <fa-icon *ngIf="!toDoDoneShow" [icon]="faDown"></fa-icon>
                    <fa-icon *ngIf="toDoDoneShow" [icon]="faUp"></fa-icon>
                </span>
            </div>
        </h3>
        <div *ngIf="toDoDoneShow" class="todo-elements">
            <app-template-todo (ping)="update($event)" [toDo$]="toDo" *ngFor="let toDo of $todosdone"></app-template-todo>
        </div>
    </div>
</div>

// React.js/todolist/src/components/Pagelist.jsx
import React from 'react';
import TodoForm from './TodoForm';
import Todo from './Todo';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronUp, faChevronDown } from '@fortawesome/free-solid-svg-icons';
import LocalStorageService from '../services/localstorage.service';

let lss = LocalStorageService.getInstance();

const Pagelist = () => {
    const [toDoShow, setToDoShow] = React.useState(true)
    const [toDoDoneShow, setToDoDoneShow] = React.useState(false)
    const [todos, setTodos] = React.useState(lss.getTodos(false))
    const [todosdone, setTodosdone] = React.useState(lss.getTodos(true))
    const [todosLength, setTodosLength] = React.useState(0)
    const [todosdoneLength, setTodosDoneLength] = React.useState(0)
    
    React.useEffect(() => {
        setTodosLength(todos.length)
    }, [todos])
    React.useEffect(() => {
        setTodosDoneLength(todosdone.length)
    }, [todosdone])

    const addTodo = ({label}) => {
        const newTodo = {
            id: lss.getNextId(),
            label: label,
            status: false
        }
        lss.addTodo(newTodo)
        setTodos([...todos, newTodo])
    }

    const deleteTodo = (id) => {
        setTodos(todos.filter((todo) => todo.id !== id))
        lss.removeTodo(id)
    }
    const deleteTododone = (id) => {
        setTodosdone(todosdone.filter((todo) => todo.id !== id))
        lss.removeTodo(id)
    }

    const editTodo = (newTodo) => {
        let allTodos = lss.getAllTodos()
        allTodos.forEach(el => {
            if(el.id === newTodo.id){
                allTodos = allTodos.filter((todo) => todo.id !== newTodo.id)
                allTodos.push(newTodo)
            }
        })
        setTodos(allTodos.filter((todo) => !todo.status))
        setTodosdone(allTodos.filter((todo) => todo.status))
        lss.editTodo(newTodo)
    }

    return (
        <div className="pagelist-template">
            <TodoForm onAddTodo={addTodo} />

            <div className="container-md">
                <div className="page-list">
                    <h3 className={!toDoShow ? 'pl-title justify-content-between' :'pl-title justify-content-between open'} onClick={() => {setToDoShow(!toDoShow)}}> 
                        <div className="left">
                            Offen
                            <span className="badge bg-secondary pl-num">{todosLength}</span>
                        </div>
                        <div className="right">
                            <span className="chevron-toggle">
                                {toDoShow ? <FontAwesomeIcon icon={faChevronUp} /> : <FontAwesomeIcon icon={faChevronDown} />}
                            </span>
                        </div>
                    </h3>
                    <div className="todo-elements" style={!toDoShow ? {display: 'none'} : {display: 'block'}}>
                        {todos.map((todo) => (
                            <Todo todo={todo} onDeleteToDo={deleteTodo} onEditTodo={editTodo} />
                        ))}
                    </div>
                </div>

                <hr />
                
                <div className="page-list">
                    <h3 className={!toDoDoneShow ? "pl-title justify-content-between" : "pl-title justify-content-between open"} onClick={() => {setToDoDoneShow(!toDoDoneShow)}}>
                        <div className="left">
                            Erledigt
                            <span className="badge bg-secondary pl-num">{todosdoneLength}</span>
                        </div>
                        <div className="right">
                            <span className="chevron-toggle">
                                {toDoDoneShow ? <FontAwesomeIcon icon={faChevronUp} /> : <FontAwesomeIcon icon={faChevronDown} />}
                            </span>
                        </div>
                    </h3>
                    <div className="todo-elements"  style={!toDoDoneShow ? {display: 'none'} : {display: 'block'}}>
                        {todosdone.map((todo) => (
                            <Todo todo={todo} onDeleteToDo={deleteTododone}  onEditTodo={editTodo} />
                        ))}
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Pagelist
