// React.js/todolist/src/App.jsx
import React from 'react';
import './App.scss';
import Pagelist from './components/Pagelist';
import Header from './components/Header';

function App() {
  return (
    <div className="App">
      <Header />
      <main className="flex-header content-main container-fluid">
          <Pagelist />
      </main>
    </div>
  )
}

export default App;

// Angular/ToDoList/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  title = 'MyTodoList'; 
}

<app-template-header></app-template-header>
<main class="flex-header content-main container-fluid">
    <app-page-list></app-page-list>
</main>
